#ifndef ARDUCAM_EVK_SDK_VERSION_
#define ARDUCAM_EVK_SDK_VERSION_

#define ARDUCAM_EVK_SDK_MAJOR_VERSION (1)
#define ARDUCAM_EVK_SDK_MINOR_VERSION (0)
#define ARDUCAM_EVK_SDK_PATCH_VERSION (7)
#define ARDUCAM_EVK_SDK_VERSION "1.0.7"

#endif  // ARDUCAM_EVK_SDK_VERSION_
